username_textbox="userName"
password_textbox="password"
login_button="submit"
welcome_msg_box="xpath=//h3[text()='Login Successfully']"
cookie_msg="xpath=//h1[contains(text(),'Manage Your')]"
accept_all="xpath=//span[contains(text(),'Accept All')]"
student_registration_btn="//button[text()='New Registration']"
submit_btn="//button[text()='Submit']"
reset_btn="//button[text()='Reset']"
student_id="//input[@name='sid']"
student_first_name="//input[@name='sfname']"
student_last_name="//input[@name='slname']"
student_dob="//input[@name='dob']"
student_gov_id_type='gidtype'
student_gov_id_no="//input[@name='gidno']"
student_mobile="//input[@name='mobile']"
student_emal="//input[@name='email']"
vaccine_type='vaccine'
modify_registration_btn="//button[text()='Modify Registration']"
#Vaccination drive
vaccination_drive_request_btn="//span[text()='Request']/parent::button"
vacc_date="//input[@id='date']"
covaxin_count="//input[@id='numDosesC']"
covishield_count="//input[@id='numDosesCS']"
